In [2]:
import pandas as pd

In [44]:
df = pd.read_csv("The Titanic dataset.csv",header=1)
df

,sn,pclass,survived,Unnamed: 3,gender,age,family,fare,embarked,date
0,1,3,0,Mr. Anthony,male,42,0.0,7.55,NaN,01-Jan-90
1,1,3,0,Mr. Anthony,male,42,0.0,7.55,NaN,01-Jan-90
2,2,3,0,Master. Eugene Joseph,male,?,2.0,20.25,S,02-Jan-90
3,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2.0,**,S,03-Jan-90
4,4,3,1,"Abbott, Mr. Rossmore Edward",female,35,2.0,20.25,S,04-Jan-90
...,...,...,...,...,...,...,...,...,...,...
1296,1296,2,0,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24,0.0,13,S,19-Jul-93
1297,1297,3,0,"Zabour, Miss. Hileni",female,14.5,1.0,14.4542,C,20-Jul-93
1298,1298,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0.0,7.225,C,21-Jul-93
1299,1299,3,0,"Zakarian, Mr. Ortin",male,27,0.0,7.225,C,22-Jul-93
1300,1300,3,0,"Zimmerman, Mr. Leo",male,29,0.0,7.875,S,23-Jul-93

In [22]:
df.columns[0]

'sn'

In [5]:

df.columns

Index(['sn', 'pclass', 'survived', 'Unnamed: 3', 'gender', 'age', 'family',
       'fare', 'embarked', 'date'],
      dtype='object')

In [8]:
df.columns

Index(['sn', 'pclass', 'survived', 'Unnamed: 3', 'gender', 'age', 'family',
       'fare', 'embarked', 'date'],
      dtype='object')

In [10]:
print(df.shape)

(1301, 10)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sn          1301 non-null   int64
 1   pclass      1301 non-null   int64
 2   survived    1301 non-null   int64
 3   Unnamed: 3  1301 non-null   object
 4   gender      1300 non-null   object
 5   age         1044 non-null   object
 6   family      1299 non-null   float64
 7   fare        1299 non-null   object
 8   embarked    1295 non-null   object
 9   date        1301 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 101.8+ KB

In [12]:
df.describe()

                sn       pclass     survived       family
count  1301.000000  1301.000000  1301.000000  1299.000000
mean    650.000769     2.289777     0.384320     0.889915
std     375.709330     0.838384     0.486621     1.588008
min       1.000000     1.000000     0.000000     0.000000
25%     325.000000     2.000000     0.000000     0.000000
50%     650.000000     3.000000     0.000000     0.000000
75%     975.000000     3.000000     1.000000     1.000000
max    1300.000000     3.000000     1.000000    10.000000

what is loc and iloc

In [23]:
df.loc[1:4]

,sn,pclass,survived,Unnamed: 3,gender,age,family,fare,embarked,date
1,1,3,0,Mr. Anthony,male,42,0.0,7.55,NaN,01-Jan-90
2,2,3,0,Master. Eugene Joseph,male,?,2.0,20.25,S,02-Jan-90
3,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2.0,**,S,03-Jan-90
4,4,3,1,"Abbott, Mr. Rossmore Edward",female,35,2.0,20.25,S,04-Jan-90

In [21]:
a=df.loc[1:3, ["age", "gender"]]
a

   age gender
1   42   male
2    ?   male
3  NaN    NaN

In [26]:
a=df.loc[:, ["gender","age"]]

In [31]:
b = a[a["age"] > 30]
b

      gender   age
0       male  42.0
1       male  42.0
4     female  35.0
13    female  40.0
23      male  35.0
...      ...   ...
1285  female  31.0
1288    male  36.0
1291    male  62.0
1294  female  36.0
1295    male  45.5

[438 rows x 2 columns]

In [39]:
df.isnull().sum()

sn              0
pclass          0
survived        0
Unnamed: 3      0
gender          1
age           257
family          2
fare            2
embarked        6
date            0
dtype: int64

In [34]:
print(df["age"].unique())

['42' '?' nan '35' '16' '25' '30' '28' '20' '18' '26' '40' '0.83' '24'
 '29' '0.92' '2' '32' '19' '48' '4' '6' '17' '38' '9' '11' '39' '27' '63'
 '34' '36' '53' '71' '57' '5' '3' '13' '23' '45' '21' '47' '33' '0.75'
 '80' '22' '51' '50' '1' '12' '37' '58' '41' '15' '60' '44' '59' '18.5'
 '14' '54' '49' '76' '46' '52' '8' '31' '64' '70.5' '43' '55' '70' '22.5'
 '36.5' '65' '40.5' '10' '0.67' '23.5' '62' '7' '32.5' '34.5' '61' '20.5'
 '30.5' '55.5' '0.17' '28.5' '45.5' '56' '38.5' '14.5' '24.5' '60.5' '67'
 '74' '11.5' '66' '26.5']

In [41]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")

Data cleaning and fill null values

In [46]:
df.dtypes

sn              int64
pclass          int64
survived        int64
Unnamed: 3     object
gender         object
age            object
family        float64
fare           object
embarked       object
date           object
dtype: object

In [47]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")

In [48]:
df.dtypes

sn              int64
pclass          int64
survived        int64
Unnamed: 3     object
gender         object
age           float64
family        float64
fare           object
embarked       object
date           object
dtype: object

In [51]:
df["age"]= df["age"].fillna(df["age"].mean())
a=df["age"].isnull().sum()
a

np.int64(0)

In [52]:
df.dtypes

sn              int64
pclass          int64
survived        int64
Unnamed: 3     object
gender         object
age           float64
family        float64
fare           object
embarked       object
date           object
dtype: object

In [53]:
uni = df["fare"].unique()
uni

array(['7.55', '20.25', '**', '7.65', '24', '7.925', '7.2292', '7.25',
       '8.05', '9.475', '9.35', '18.7875', '13', '7.8875', '7.05',
       '211.3375', '151.55', '8.3', '22.525', '7.8542', '26.55', '31.275',
       '7.775', '7.7958', '11.5', '10.5', '77.9583', '0', '7.8958', '26',
       '51.4792', '17.8', '49.5042', '31.3875', '7.225', '227.525',
       '14.4583', '69.3', '15.85', '19.2583', '14.4542', '78.85', '30',
       '7.8792', '12.525', '25.925', '247.5208', '76.2917', '75.2417',
       '39', '52.5542', '4.0125', '56.4958', '221.7792', '91.0792',
       '135.6333', '7.75', '35.5', '31', '164.8667', '15.2458', '15.5',
       '262.375', '16.1', '55', '7.725', '30.5', '50.4958', '7.0458',
       '39.6', '27.7208', '7.2833', '7.8208', '6.75', '134.5', '8.6625',
       '26.2875', '29', '21', '27.4458', '512.3292', '5', '47.1', '120',
       '61.175', '53.1', '13.5', '7.7333', '86.5', '29.7', '136.7792',
       '52', '7.4958', '25.5875', '26.25', '83.1583', '7.6292', '25.7',
       '15.9', '8.1583', '71', '71.2833', '10.5167', '10.1708', '6.95',
       '14.4', '36.75', '24.15', '73.5', '17.4', '9.5', '20.575', '31.5',
       '57', '81.8583', '23', '106.425', '12.475', '32.5', '56.9292',
       '13.8583', '13.9', '6.975', '78.2667', '31.6792', '15.1',
       '31.6833', '110.8833', '26.3875', '34.375', '27.75', '263',
       '133.65', '49.5', '79.2', '7.7417', '14.5', '38.5', '211.5',
       '59.4', '89.1042', '34.6542', '20.525', '7.85', '46.9', '28.5',
       '153.4625', '63.3583', '8.3625', '9.8458', '8.85', '19.9667',
       '14.1083', '55.4417', '33', '76.7292', '42.4', '83.475', '6.8583',
       '93.5', '42.5', '8.9625', '65', '16', '51.8625', '50', '57.9792',
       '12.2875', '6.45', '90', '30.6958', '12.275', '80', '28.7125',
       '27', '15', '7.0542', '13.7917', '8.1125', '6.4958', '8.6542',
       '11.1333', '23.45', '9.825', '7.125', '8.4333', '7.5208',
       '13.4167', '12.35', '7.8292', '7.7375', '22.025', '12.1833',
       '9.5875', '10.7083', '41.5792', '9.4833', '25.9292', '25.4667',
       '12', '6.4375', '12.875', '15.55', '39.4', '45.5', '7.5792',
       '146.5208', '7.1417', '15.0458', '37.0042', '15.5792', '23.25',
       '7.7875', '8.0292', '19.5', '82.1708', nan, '57.75', '8.4583',
       '14', '9.6875', '15.7417', '30.0708', '113.275', '26.2833',
       '11.2417', '7.8', '13.8625', '6.2375', '9.225', '108.9', '3.1708',
       '8.4042', '7.3125', '25.7417', '9.2167', '8.6833', '61.9792',
       '21.075', '39.6875', '8.7125', '13.775', '7', '66.6', '15.05',
       '22.3583', '8.1375', '12.7375', '15.0333', '29.125', '18.75',
       '7.7208', '20.2125', '40.125', '7.7292', '7.575', '69.55', '9.325',
       '21.6792', '16.7', '7.7792', '55.9', '27.9', '60', '82.2667',
       '9.8375', '10.4625', '32.3208', '79.65', '8.5167', '12.65',
       '28.5375', '9.8417', '33.5', '9', '18', '34.0208', '75.25',
       '15.75', '77.2875', '61.3792', '35', '7.875'], dtype=object)

Change fare String into number

In [55]:
df["fare"] =pd.to_numeric(df["fare"],errors="coerce")

In [56]:
df.dtypes

sn              int64
pclass          int64
survived        int64
Unnamed: 3     object
gender         object
age           float64
family        float64
fare          float64
embarked       object
date           object
dtype: object

In [57]:
df.head(5)

,sn,pclass,survived,Unnamed: 3,gender,age,family,fare,embarked,date
0,1,3,0,Mr. Anthony,male,42.00000,0.0,7.55,NaN,01-Jan-90
1,1,3,0,Mr. Anthony,male,42.00000,0.0,7.55,NaN,01-Jan-90
2,2,3,0,Master. Eugene Joseph,male,29.97883,2.0,20.25,S,02-Jan-90
3,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,29.97883,2.0,NaN,S,03-Jan-90
4,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.00000,2.0,20.25,S,04-Jan-90

In [58]:
df.isnull().sum()

sn            0
pclass        0
survived      0
Unnamed: 3    0
gender        1
age           0
family        2
fare          3
embarked      6
date          0
dtype: int64

In [59]:
df = df.dropna()

In [60]:
df.isnull().sum()

sn            0
pclass        0
survived      0
Unnamed: 3    0
gender        0
age           0
family        0
fare          0
embarked      0
date          0
dtype: int64

In [61]:
df.columns

Index(['sn', 'pclass', 'survived', 'Unnamed: 3', 'gender', 'age', 'family',
       'fare', 'embarked', 'date'],
      dtype='object')

Rename of the column

In [62]:
df.rename(columns={
    'Unnamed: 3':"name"
}, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19728\1595737742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={

In [63]:
df

,sn,pclass,survived,name,gender,age,family,fare,embarked,date
2,2,3,0,Master. Eugene Joseph,male,29.97883,2.0,20.2500,S,02-Jan-90
4,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.00000,2.0,20.2500,S,04-Jan-90
5,5,3,1,"Abelseth, Miss. Karen Marie",female,16.00000,0.0,7.6500,S,05-Jan-90
6,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.00000,0.0,7.6500,S,06-Jan-90
7,7,2,0,"Abelson, Mr. Samuel",male,30.00000,1.0,24.0000,C,07-Jan-90
...,...,...,...,...,...,...,...,...,...,...
1296,1296,2,0,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.00000,0.0,13.0000,S,19-Jul-93
1297,1297,3,0,"Zabour, Miss. Hileni",female,14.50000,1.0,14.4542,C,20-Jul-93
1298,1298,3,0,"Zakarian, Mr. Mapriededer",male,26.50000,0.0,7.2250,C,21-Jul-93
1299,1299,3,0,"Zakarian, Mr. Ortin",male,27.00000,0.0,7.2250,C,22-Jul-93
1300,1300,3,0,"Zimmerman, Mr. Leo",male,29.00000,0.0,7.8750,S,23-Jul-93

In [64]:
df["age"].unique()

array([29.9788303, 35.       , 16.       , 25.       , 30.       ,
       28.       , 20.       , 18.       , 26.       , 40.       ,
        0.83     , 24.       , 29.       ,  0.92     ,  2.       ,
       32.       , 19.       , 48.       ,  4.       ,  6.       ,
       17.       , 38.       ,  9.       , 11.       , 39.       ,
       27.       , 63.       , 34.       , 36.       , 53.       ,
       71.       , 57.       ,  5.       ,  3.       , 13.       ,
       23.       , 45.       , 21.       , 47.       , 33.       ,
        0.75     , 80.       , 22.       , 51.       , 50.       ,
        1.       , 12.       , 37.       , 42.       , 58.       ,
       41.       , 15.       , 60.       , 44.       , 59.       ,
       18.5      , 14.       , 54.       , 49.       , 76.       ,
       46.       , 52.       ,  8.       , 31.       , 64.       ,
       70.5      , 43.       , 55.       , 70.       , 22.5      ,
       36.5      , 65.       , 40.5      , 10.       ,  0.67     ,
       23.5      , 62.       ,  7.       , 32.5      , 34.5      ,
       61.       , 20.5      , 30.5      , 55.5      , 28.5      ,
       45.5      , 56.       , 38.5      , 14.5      , 24.5      ,
       67.       , 74.       , 11.5      , 66.       , 26.5      ])

create a new colum and add the value

In [66]:
import numpy as np

df["bonus"] = np.where(
    (df["age"] >= 20) & (df["age"] < 30), 10000,
    np.where(
        (df["age"] >= 30) & (df["age"] < 40), 15000,
        0
    )
)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19728\2916604988.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bonus"] = np.where(

In [67]:
import numpy as np

df["bonus"] = np.where(
    (df["age"] >= 20) & (df["age"] < 30), 10000,
    np.where(
        (df["age"] >= 30) & (df["age"] < 40), 15000,
        np.where(
            df["age"] > 40, 25000,
            0
        )
    )
)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19728\4178085014.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bonus"] = np.where(

In [69]:
df.head(5)

,sn,pclass,survived,name,gender,age,family,fare,embarked,date,bonus
2,2,3,0,Master. Eugene Joseph,male,29.97883,2.0,20.25,S,02-Jan-90,10000
4,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.00000,2.0,20.25,S,04-Jan-90,15000
5,5,3,1,"Abelseth, Miss. Karen Marie",female,16.00000,0.0,7.65,S,05-Jan-90,0
6,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.00000,0.0,7.65,S,06-Jan-90,10000
7,7,2,0,"Abelson, Mr. Samuel",male,30.00000,1.0,24.00,C,07-Jan-90,15000

Change data type
as.type(int)
if the column having numeric then only possible
if the data set having nan it is not possible

In [70]:
df["age"] = df["age"].astype(int)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19728\3261694546.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["age"] = df["age"].astype(int)

In [71]:
df.head(5)

,sn,pclass,survived,name,gender,age,family,fare,embarked,date,bonus
2,2,3,0,Master. Eugene Joseph,male,29,2.0,20.25,S,02-Jan-90,10000
4,4,3,1,"Abbott, Mr. Rossmore Edward",female,35,2.0,20.25,S,04-Jan-90,15000
5,5,3,1,"Abelseth, Miss. Karen Marie",female,16,0.0,7.65,S,05-Jan-90,0
6,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25,0.0,7.65,S,06-Jan-90,10000
7,7,2,0,"Abelson, Mr. Samuel",male,30,1.0,24.00,C,07-Jan-90,15000

In [ ]:
#count numberof rows
count = df[df["age"] < 14].shape[0]
print(count)

95

Find less than 14 age people details

In [76]:
#see the rows data
df[df["age"] < 14].head()

,sn,pclass,survived,name,gender,age,family,fare,embarked,date,bonus
14,14,3,1,"Aks, Master. Philip Frank",male,0,1.0,9.350,S,14-Jan-90,0
24,24,1,1,"Allison, Master. Hudson Trevor",male,0,3.0,151.550,S,24-Jan-90,0
25,25,1,0,"Allison, Miss. Helen Loraine",female,2,3.0,151.550,S,25-Jan-90,0
32,32,3,0,"Andersson, Master. Sigvard Harald Elias",male,4,6.0,31.275,S,01-Feb-90,0
33,33,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6,6.0,31.275,S,02-Feb-90,0

In [77]:
df.duplicated

<bound method DataFrame.duplicated of         sn  pclass  survived                                    name  gender  \
2        2       3         0                   Master. Eugene Joseph    male
4        4       3         1             Abbott, Mr. Rossmore Edward  female
5        5       3         1             Abelseth, Miss. Karen Marie  female
6        6       3         1           Abelseth, Mr. Olaus Jorgensen    male
7        7       2         0                     Abelson, Mr. Samuel    male
...    ...     ...       ...                                     ...     ...
1296  1296       2         0  Yrois, Miss. Henriette ("Mrs Harbeck")  female
1297  1297       3         0                    Zabour, Miss. Hileni  female
1298  1298       3         0               Zakarian, Mr. Mapriededer    male
1299  1299       3         0                     Zakarian, Mr. Ortin    male
1300  1300       3         0                      Zimmerman, Mr. Leo    male

      age  family     fare embarked       date  bonus
2      29     2.0  20.2500        S  02-Jan-90  10000
4      35     2.0  20.2500        S  04-Jan-90  15000
5      16     0.0   7.6500        S  05-Jan-90      0
6      25     0.0   7.6500        S  06-Jan-90  10000
7      30     1.0  24.0000        C  07-Jan-90  15000
...   ...     ...      ...      ...        ...    ...
1296   24     0.0  13.0000        S  19-Jul-93  10000
1297   14     1.0  14.4542        C  20-Jul-93      0
1298   26     0.0   7.2250        C  21-Jul-93  10000
1299   27     0.0   7.2250        C  22-Jul-93  10000
1300   29     0.0   7.8750        S  23-Jul-93  10000

[1292 rows x 11 columns]>

duplicate value is there are not 
keep if used it will take other than 1

In [ ]:
check duplicate is present or not

In [79]:
df[df.duplicated(subset=["age","name"],keep=False)]

Empty DataFrame
Columns: [sn, pclass, survived, name, gender, age, family, fare, embarked, date, bonus]
Index: []

In [80]:
df.duplicated(subset=["age", "name"]).sum()

np.int64(0)